<a href="https://colab.research.google.com/github/WaquarH/data-science-work/blob/main/waquar_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2>Name - Waquar Haseeb<br>
sixth semester<br>
NLP Assignment <br>
topic:- preprocessing and text document matrix</h2>

**why we need preprocessing?**<br>
Text preprocessing helps us normalize our input data and reduce noises. It could facilitate our analysis; however, improper use of preprocessing could also make us lose important information in our raw data. 

In [3]:
#collection of documents
para_1 = "Waquar Haseeb is writing a poem about the river. And eating something spicy"
para_2 = "i believe that he is not writing instead he is singing "
para_3 = "i believe that he is shouting instead of singing"
para_4= "he is just humming"

In [4]:
docs = [para_1, para_2, para_3,para_4]
docs

['Waquar Haseeb is writing a poem about the river. And eating something spicy',
 'i believe that he is not writing instead he is singing ',
 'i believe that he is shouting instead of singing',
 'he is just humming']

**Tokenization**<br>
A tokenizer splits a sentence into words or a document into sentences. Most of them are implemented by regular expressions.

In [24]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [6]:
from nltk.tokenize import sent_tokenize, word_tokenize, wordpunct_tokenize
import string

In [7]:
for i in docs:
  print(i)

Waquar Haseeb is writing a poem about the river. And eating something spicy
i believe that he is not writing instead he is singing 
i believe that he is shouting instead of singing
he is just humming


In [8]:
tokens=[]
for i in docs:
  for j in (sent_tokenize(i)):
    tokens.append(j)

In [9]:
tokens

['Waquar Haseeb is writing a poem about the river.',
 'And eating something spicy',
 'i believe that he is not writing instead he is singing',
 'i believe that he is shouting instead of singing',
 'he is just humming']

In [10]:
# remove all punctuations
token2=[]
trantab = str.maketrans(dict.fromkeys(list(string.punctuation)))
for i in tokens:
  for j in (word_tokenize(i.translate(trantab))):
    token2.append(j) # word level tokens

In [11]:
token2

['Waquar',
 'Haseeb',
 'is',
 'writing',
 'a',
 'poem',
 'about',
 'the',
 'river',
 'And',
 'eating',
 'something',
 'spicy',
 'i',
 'believe',
 'that',
 'he',
 'is',
 'not',
 'writing',
 'instead',
 'he',
 'is',
 'singing',
 'i',
 'believe',
 'that',
 'he',
 'is',
 'shouting',
 'instead',
 'of',
 'singing',
 'he',
 'is',
 'just',
 'humming']

**case folding**<br>
It is a super easy operation and the purpose is to normalize words into the same form in case (e.g. “The” and “the” will be treated as two different unigrams if no case-folding)

In [14]:
# tokenize and lowercase
tokens_lowercase=[]
for i in token2:
  for t in word_tokenize(i):
    tokens_lowercase.append(t.lower())
print(tokens_lowercase)

['waquar', 'haseeb', 'is', 'writing', 'a', 'poem', 'about', 'the', 'river', 'and', 'eating', 'something', 'spicy', 'i', 'believe', 'that', 'he', 'is', 'not', 'writing', 'instead', 'he', 'is', 'singing', 'i', 'believe', 'that', 'he', 'is', 'shouting', 'instead', 'of', 'singing', 'he', 'is', 'just', 'humming']


**Stopwords filtering**<br>
In computing, stop words are words which are filtered out before or after processing of natural language data (text). Though “stop words” usually refers to the most common words in a language, there is no single universal list of stop words used by all natural language processing tools, and indeed not all tools even use such a list

In [15]:
from nltk.corpus import stopwords

In [20]:
# remove stopwords
sw_set = set(stopwords.words('english'))
tokens = [t for t in tokens_lowercase if t not in sw_set]
print(tokens)

['waquar', 'haseeb', 'writing', 'poem', 'river', 'eating', 'something', 'spicy', 'believe', 'writing', 'instead', 'singing', 'believe', 'shouting', 'instead', 'singing', 'humming']


**Lemmatization**<br>
Lemmatization in linguistics is the process of grouping together the inflected forms of a word so they can be analyzed as a single item, identified by the word’s lemma, or dictionary form. Unlike stemming, lemmatization depends on correctly identifying the intended part of speech and meaning of a word in a sentence, as well as within the larger context surrounding that sentence, such as neighboring sentences or even an entire document.<br>
<br>
The difference between lemmatization and stemming is that lemmatization utilizes dictionary-like resources to convert a word into its basic form

In [21]:
from nltk.stem import WordNetLemmatizer

In [22]:
# lemmatize by the WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

In [25]:
print([wordnet_lemmatizer.lemmatize(d, pos='v') for d in tokens]) # POS = verb
print([wordnet_lemmatizer.lemmatize(d, pos='a') for d in tokens]) # POS = adjective

['waquar', 'haseeb', 'write', 'poem', 'river', 'eat', 'something', 'spicy', 'believe', 'write', 'instead', 'sing', 'believe', 'shout', 'instead', 'sing', 'hum']
['waquar', 'haseeb', 'writing', 'poem', 'river', 'eating', 'something', 'spicy', 'believe', 'writing', 'instead', 'singing', 'believe', 'shouting', 'instead', 'singing', 'humming']


In [26]:
tokens = [wordnet_lemmatizer.lemmatize(d, pos='v') for d in tokens]

**Document term Matrix**<br>
A document-term matrix is a mathematical matrix that describes the frequency of terms that occur in a collection of documents. In a document-term matrix, rows correspond to documents in the collection and columns correspond to terms.

In [38]:
# Construct a term-document matrix
# here as a Python dictionary for ease of interpretability

doc_term_matrix = {}

for term in tokens:
    doc_term_matrix[term] = []
    
    for doc in tokens:
        if term in doc:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)

In [39]:
doc_term_matrix

{'believe': [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
 'eat': [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 'haseeb': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 'hum': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 'instead': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
 'poem': [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 'river': [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 'shout': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 'sing': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
 'something': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 'spicy': [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 'waquar': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 'write': [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]}

In [48]:
# The query to find all documents containing "waquar" AND "sing"
# Is just a bitwise AND:

import numpy as np

docs_array = np.array(tokens, dtype='object')

v1 = np.array(doc_term_matrix['waquar'])    
v2 = np.array(doc_term_matrix['haseeb'])

print(v1)
print(v2)
print('-------')
v3 = v1 | v2
print(v3)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
-------
[1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [49]:
# We can now get the matching documents from our corpus with the result
[doc for doc in v3 * docs_array if doc]

['waquar', 'haseeb']

In [51]:
v1 = np.array(doc_term_matrix['eat'])    
v2 = np.array(doc_term_matrix['spicy'])

print(v1)
print(v2)
print('-------')
v3 = v1 | v2
print(v3)

[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
-------
[0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]


In [52]:
[doc for doc in v3 * docs_array if doc]

['eat', 'spicy']

<strong><h3>And doc_term_matrix is the final result of the task.</h3></strong>

Notebook by Waquar Haseeb